import ranking

#print("TF-IDF:")
#print("vineyard:")
#print(ranking.tf_idf("vineyard", 5))
#print("merlot:")
#print(ranking.tf_idf("merlot", 5))
#print("blueberry:")
#print(ranking.tf_idf("blueberry", 5))
#print("merlot blueberry:")
#print(ranking.tf_idf("merlot blueberry", 5))
#print("blueberry merlot blueberry:")
#print(ranking.tf_idf("blueberry merlot blueberry", 5))

#print("BM25")
#print("vineyard:")
#print(ranking.bm25("vineyard", 5))
#print("merlot:")
#print(ranking.bm25("merlot", 5))
#print("blueberry:")
#print(ranking.bm25("blueberry", 5))
#print("merlot blueberry:")
#print(ranking.bm25("merlot blueberry", 5))
#print("blueberry merlot blueberry:")
#print(ranking.bm25("blueberry merlot blueberry", 5))

print(ranking.containing('merlot'))
print(ranking.containing('blueberry'))